export { default as api } from "./client";
export * from "./auth";
export * from "./admin";
export * from "./analytics";
export * from "./appointment";
export * from "./doctor";
export * from "./healthMetric";
export * from "./leave";
export * from "./medicalRecord";
export * from "./patient";
export * from "./payment";
export * from "./review";
export * from "./user";
